linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  staticcheck:
    checks: ["all"]

run:
  timeout: 2m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - ineffassign
    - unused

issues:
  max-same-issues: 3
  max-issues-per-linter: 0
  exclude-rules:
    - linters:
        - gofmt
      text: "file is not formatted"
    - path: "vendor/.*"
      linters:
        - all
    - path: "/usr/local/go/src/.*"
      linters:
        - all
