name: Build app_go

on:
  push:
    paths:
      - 'app_go/**'
      - '.github/workflows/app_go.yaml'
  pull_request:
    paths:
      - 'app_go/**'
      - '.github/workflows/app_go.yaml'

jobs:
  lint:
    timeout-minutes: 2
    defaults:
      run:
        working-directory: app_go
    name: Run golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: golangci-lint run ./...

  test:
    timeout-minutes: 5
    defaults:
      run:
        working-directory: app_go
    name: Run Go tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

  snyk_check:
    needs: [lint, test]
    timeout-minutes: 5
    name: Run Snyk
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        with:
          args: --skip-unresolved app_go/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build_push:
    timeout-minutes: 10
    defaults:
      run:
        working-directory: app_go
    needs: [lint, test, snyk_check]
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            UID=10001
            GID=10001
          tags: "${{ secrets.DOCKER_USERNAME }}/app_go:latest"
          context: "{{defaultContext}}:app_go"
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/app_go:latest
          cache-to: type=inline
